function output = feature_extract(frame_AccTempEDA, frame_SpO2HR)
% input: AccTempEDA, SpO2HR
% output: feature matrix of size (5+2)*4, 
% 5column-->AccTempEDA, 2column-->SpO2HR,4-->features(min/max/mean/change)
%

%% AccTempEDA
L1 = 48; R1 = 24;
[acx_mean, acx_max, acx_min, acx_change] = td_analysis(frame_AccTempEDA(:, 1), L1, R1);
[acy_mean, acy_max, acy_min, acy_change] = td_analysis(frame_AccTempEDA(:, 2), L1, R1);
[acz_mean, acz_max, acz_min, acz_change] = td_analysis(frame_AccTempEDA(:, 3), L1, R1);
[temp_mean, temp_max, temp_min, temp_change] = td_analysis(frame_AccTempEDA(:, 4), L1, R1);
[EDA_mean, EDA_max, EDA_min, EDA_change] = td_analysis(frame_AccTempEDA(:, 5), L1, R1);

%% SpO2HR
L2 = 6; R2 = 3;
[SPO2_mean, SPO2_max, SPO2_min, SPO2_change] = td_analysis(frame_SpO2HR(:, 1), L2, R2);
[HR_mean, HR_max, HR_min, HR_change] = td_analysis(frame_SpO2HR(:, 2), L2, R2);

%% Create table according to Code Generation (Restriction) for Tables
table_name = {...
            'acx_mean', 'acx_max', 'acx_min', 'acx_change', ...
            'acy_mean', 'acy_max', 'acy_min', 'acy_change', ...
            'acz_mean', 'acz_max', 'acz_min', 'acz_change', ...
            'temp_mean', 'temp_max', 'temp_min', 'temp_change', ...
            'EDA_mean', 'EDA_max', 'EDA_min', 'EDA_change', ...
            'SPO2_mean', 'PO2_max', 'SPO2_min', 'SPO2_change', ...
            'HR_mean', 'HR_max', 'HR_min', 'HR_change'};

output = table(...
            acx_mean, acx_max, acx_min, acx_change, ...
            acy_mean, acy_max, acy_min, acy_change, ...
            acz_mean, acz_max, acz_min, acz_change, ...
            temp_mean, temp_max, temp_min, temp_change, ...
            EDA_mean, EDA_max, EDA_min, EDA_change, ...
            SPO2_mean, SPO2_max, SPO2_min, SPO2_change, ...
            HR_mean, HR_max, HR_min, HR_change, ...
            'VariableNames', table_name);
end